### ISSUE TITLE
ASG Tags

### ISSUE THREAD

**Issue by kewubenduben** [thecantero/cfn-sampling#3]
I'd like to get an idea first on what tags we want to pass on ASG.

**Comment by nmzakib** [comment]
something like

Key : Name
Value : 5. SMS Gateway

**Comment by kewubenduben** [comment]
@nmzakib,

I'm not entirely inclined on the idea of adding a TAG parameter in the template due to following:
- cloudformation has a tags parameter that you can pass for the whole stack.

```
taken from "aws cloudformation create-stack help"

       --tags (list)
          Key-value pairs to associate with  this  stack.  AWS  CloudFormation
          also  propagates these tags to the resources created in the stack. A
          maximum number of 10 tags can be specified.

       Shorthand Syntax:

          Key=string,Value=string ...

       JSON Syntax:

          [
            {
              "Key": "string",
              "Value": "string"
            }
            ...
          ]
```
- Currently, I haven't known or found a way to handle List<kv> type of entry for parametrs in CF. Which would make us resort into adding single/hard-coded parameter for every key and value we want to pass.

Let me know your thoughts.

**Comment by nmzakib** [comment]
Alright. We can live with using cloudformation's tag for the whole stack for now. It is not the most accurate tagging since we prefer to tag the LBs separately from the Instances but it is better than hard-coding the parameters.

**Comment by kewubenduben** [comment]
Got it. Thanks. Closing this.
