### ISSUE TITLE
EBS on Launch Configuration

### ISSUE THREAD

**Issue by kewubenduben** [thecantero/cfn-sampling#6]
Add block device mappings on Launch Configuration.

**Comment by kewubenduben** [comment]
@nmzakib

Please review. Currently supports 2 EBS. 1 for main and 1 for extra. Please check.

**Comment by nmzakib** [comment]
I can't find this

**Comment by kewubenduben** [comment]
Checked #7  ?

**Comment by nmzakib** [comment]
Hello,

For the EBS mapping, since we already have the AMI which carries EBS with it is it doable to just specify additional EBS as needed? It seems to me that the current implementation will also change the primary volume statistics. Although i did not manage to successfully try it out after seeing this error when creating the autoscalinggroup (Logical ID: Appservergroup):

Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

**Comment by kewubenduben** [comment]
Yes, It is preferred to have only the extra EBS. I'll have it.

Regarding the signal init. I believe you need to have something like this on your instance INIT 

```
export AWS_DEFAULT_OUTPUT=text
export AWS_DEFAULT_REGION=ap-southeast-1
yum update -y aws-cfn-bootstrap
STACKID=$(aws cloudformation describe-stacks --stack-name webserver --query 'Stacks[0].StackId')
/opt/aws/bin/cfn-signal -e $?          --stack $STACKID        --resource AppServerGroup          --region ap-southeast-1
```

On my testing, I've had that on my userdata, 
- [cfn-signal](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-signal.html) 
- For [Windos](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-windows-stacks-bootstrapping.html)

**Comment by kewubenduben** [comment]
I've removed support on attaching a Main block device.

https://github.com/thecantero/cfn-sampling/commit/3aac439267724d28b66836e1c48d25c6bec34111

**Comment by nmzakib** [comment]
great. will try again soon. I have a few things to clarify with you

should my user data still start with  ' #!/bin/bash ' ?

i'm still seeing that same error after supplying the userdata with #!/bin/bash appended at the beginning

**Comment by kewubenduben** [comment]
can you post your userdata here? Here's what my userdata looks like.

```
"ParameterValue": "#!/bin/bash -xe\n# Set CLI Output to text\nexport AWS_DEFAULT_OUTPUT=text\nexport AWS_DEFAULT_REGION=ap-southeast-1\nyum update -y aws-cfn-bootstrap\nSTACKID=$(aws cloudformation describe-stacks --stack-name webserver --query 'Stacks[0].StackId' --output text)\n/opt/aws/bin/cfn-init -v          --stack $STACKID        --resource LaunchConfig          --configsets full_install          --region ap-southeast-1\n/opt/aws/bin/cfn-signal -e $?          --stack $STACKID        --resource AppServerGroup          --region ap-southeast-1\n# Set Instance Identity URI\nEC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)\nINSTANCE_ID=$(/usr/bin/curl -s http://169.254.169.254/latest/meta-data/instance-id)\nMANAGEMENTSUBNET=$(aws ec2 describe-subnets --filters Name=availabilityZone,Values=$EC2_AVAIL_ZONE          --query 'Subnets[].[SubnetId]' | egrep 'subnet-085da97e|subnet-53fb0037'\nMANAGEMENT_ENI=$(aws ec2 create-network-interface --description 'My Management interface'          --subnet-id $MANAGEMENTSUBNET --groups 'sg-af6602cb'  --query 'NetworkInterface.NetworkInterfaceId')\naws ec2 attach-network-interface --network-interface-id $MANAGEMENT_ENI --instance-id $INSTANCE_ID --device-index 1\n"
```

**Comment by nmzakib** [comment]
#!/bin/bash
export AWS_DEFAULT_OUTPUT=text
export AWS_DEFAULT_REGION=ap-southeast-1
yum update -y aws-cfn-bootstrap
STACKID=$(aws cloudformation describe-stacks --stack-name webserver --query 'Stacks[0].StackId')
/opt/aws/bin/cfn-signal -e $?          --stack $STACKID        --resource AppServerGroup          --region ap-southeast-1

Can you explain a little bit on this? Like why it has to include many parameters

**Comment by nmzakib** [comment]
I still failed to create the stack even after using your user data. Care to shed some light?

**Comment by kewubenduben** [comment]
Try to use this user-data

```
#!/bin/bash -xe
# Set CLI Output to text
export AWS_DEFAULT_OUTPUT=text
export AWS_DEFAULT_REGION=ap-southeast-1
yum update -y aws-cfn-bootstrap
STACKID=$(aws cloudformation describe-stacks --stack-name webserver --query 'Stacks[0].StackId' --output text)
/opt/aws/bin/cfn-signal -e $?          --stack $STACKID        --resource AppServerGroup          --region ap-southeast-1

```

NOTE: replace the --stack-name `webserver` entry to match the name of your stack.

**Comment by kewubenduben** [comment]
@nmzakib 

It seems that I currently can't find a way to pass a type: textarea for cloudformation.

I have to options that we may have to choose.
- passing the userdata as base64 encoded 
- passing the userdata as List of strings.... Comma Delimited.  Comma instead of `\n`. This works, but our problem is... we may encounter `comma`s in our userdata in the future, which will break.

I'd recommend the base64 encoded. Let me know your thoughts.

**Comment by nmzakib** [comment]
We can close this
