### ISSUE TITLE
JSON Validate error.

### ISSUE THREAD

**Issue by kewubenduben** [thecantero/cfn-sampling#8]
@nmzakib

Per your problem on template [Validation](https://lh5.googleusercontent.com/-GxUlme-A5_I/V2KhOsDW0nI/AAAAAAAAC24/ZmxDx7aiS_IuuhxsWjbTirvISEq3ecpSACL0B/w666-h100-no/2016-06-16.png). 

I'm curious, were you using windows? Could it be possible that when you cloned or copy the CF template, you had a file line-ending of Windows format?

Kindly check because AFAIK, that's a common problem I encountered long ago.

I've tested the CF template here both validating and actual creation of stacks, no validation issues so far.

**Comment by nmzakib** [comment]
I am using windows yes. But we can close this. It is fine now

**Comment by kewubenduben** [comment]
great
